
### Teaching Assistant
<br>
<ul>
<li><strong> Introduction to Economic Reasoning, Barnard College</strong> (Fall 2021, Spring 2022) </li>

Undergraduate Course taught by  <a href="http://www.columbia.edu/~rs328/">Professor Sethi</a> following <a href="https://www.core-econ.org/the-economy/book/text/0-3-contents.html">CORE</a>.<br>
Teaching Evaluations: [Fall 2022](ECONBC1003-001-2022-3-INTROTOECONOMICREASONING-MariaBelenHipola.pdf) | [Spring 2023](ECONBC1003-002-2023-1-INTROTOECONOMICREASONING-MariaBelenHipola.pdf)
<br>

<ul>
Selected Comments:
<br>
<em>
-Belen was amazing! Not only is she clearly very smart, she is kind, cares about the students, and is very accessible. She made me feel like I had someone in my corner in this course. I can't say
enough positive things!
<br>
-I love Belen. She is the best TA I have ever had. She was very effective in teaching the class material.
<br>
-Belen was great! I regularly attend her recitations and office hours and I find she is extremely effective in helping students translate what we learned in class to actual questions we might face. She
is super patient and knowledgable, and I know that has helped so many students actually understand the subject matter.
</em>
</ul>
</ul>

